server:
  port: 8090
  
spring:
   application:
      name: gateway-produits-service
  
eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:9102/eureka/

  cloud:
    gateway:
      routes:
      - id: produits
        uri: http://localhost:9001/
        predicates:
        - Path=/Produits/**
      - id: produits2
        uri: http://localhost:9012/
        predicates:
        - Path=/Produits2/**